"""Propose exact labels for the graph. This exporter is NOT trusted.

All labels must pass the Lean mathematical input checker. The old independent
audit is used solely to produce candidates and catch exporter mistakes early.
"""
from pathlib import Path
from fractions import Fraction as Q
import importlib.util
import json
import sys

HERE = Path(__file__).resolve().parents[1]
ROOT = HERE.parents[1]
SPEC = importlib.util.spec_from_file_location("proposal_arithmetic", ROOT / "Berstein/audit/independent_input.py")
P = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = P
SPEC.loader.exec_module(P)


def rat(q):
    q = Q(q)
    return str(q.numerator) if q.denominator == 1 else f"({q.numerator}/{q.denominator})"


def quad(q):
    return f"⟨{rat(q.a)}, {rat(q.b)}⟩"


def main():
    data = P.parse_input(ROOT / "Freiman/data/graph_wide.dat")
    meta = json.loads((ROOT / "Freiman/data/graph_wide.meta.json").read_text())
    verified = P.audit_semantics(data, meta)
    out = ["import Berstein.SemanticData", "", "-- Generated by scripts/export_semantics.py; labels are untrusted input.",
           "namespace Berstein.GraphMeaning", "", "def originalMeaning : Data := {", "  sides := #["]
    for i, (s, parity, suffix) in enumerate(meta["side_keys"]):
        raw = [None] * len(data["sides"][i]["tails"])
        for w, record in zip(meta["extensions"], data["sides"][i]["extensions"]):
            if record is None:
                continue
            qchild = P.state(P.BAD[:s] + tuple(w))
            ends = sorted(P.cf(w, P.extreme(qchild, minimum)) for minimum in (True, False))
            if parity:
                ends.reverse()
            for j, value in zip(record["endpoints"], ends):
                if raw[j] is not None and raw[j] != value:
                    raise ValueError("Endpoint alias mismatch")
                raw[j] = value
        assert all(v is not None for v in raw)
        lo, hi = verified["shapes"][i]
        out.append(f"    {{ state := {s}, shape := ⟨{rat(lo)}, {rat(hi)}⟩, raw := #[" + ", ".join(map(quad, raw)) + "] },")
    out.extend(["  ]", "  extensions := #["])
    out.extend("    [" + ", ".join(map(str, w)) + "]," for w in meta["extensions"])
    out.extend(["  ]", "  constants := #["])
    constants = verified["constants"]
    out.extend("    " + quad(constants.get(i, P.Exact())) + "," for i in range(max(constants) + 1))
    out.extend(["  ]", "}", "", "end Berstein.GraphMeaning", ""])
    dest = HERE / "Berstein/Data/Meaning.lean"
    dest.parent.mkdir(exist_ok=True)
    dest.write_text("\n".join(out))
    print(json.dumps({"path": str(dest), "bytes": dest.stat().st_size,
                      "sides": len(data["sides"]), "extensions": len(meta["extensions"])}))


if __name__ == "__main__":
    main()
